### ISSUE TITLE
Wont save changes to the widget contents

### ISSUE THREAD

**Issue by lmartins** [sdsweb/note#13]
Not sure what is going but i've seen this issue before.
I make changes to the widget contents but then, when I press save I lose all the changes made.

Have you seen this before, is there anything I can do about it?

**Comment by sdsweb** [comment]
@lmartins are you getting any warnings in the console of your developer tools when this happens?

**Comment by lmartins** [comment]
Yeah, I do have a JS error in the console, which only happens in the customiser. Let me have a look into that and report back what I find. Thanks Matt

**Comment by lmartins** [comment]
Im getting a JS error on the site main JS file and then another with the `note-customizer.js` script. Probably the first one is causing the second, so my first step will be trying to remove that.

![screenshot 2015-10-15 20 17 58](https://cloud.githubusercontent.com/assets/151981/10524905/e1337dbc-7379-11e5-8a89-1af4d1da4812.png)

Will let you now what I find. Thanks.

**Comment by lmartins** [comment]
Solved the JS error my code was outputting but the error regarding note is still being shown:
https://www.dropbox.com/s/fv1g05zaur0fyx9/Screenshot%202015-10-16%2010.52.26.png?dl=0

Any ideias of what might be?

**Comment by scottsousa** [comment]
Hi Luis,

We're working on pushing a new update to Note soon that will add a few enhancements and fix a couple of bugs. As for this particular JavaScript error, we're not able to replicate it on our end.

We have run into similar issues when themes did not specify `before_widget` and `after_widget` wrapper elements with the proper attributes (mainly the CSS class). It's important for the `class` attribute to be defined in `before_widget` because Note Widgets add a `note-widget` CSS class to that wrapper element when the widget is called on the front-end. We use this class when the TinyMCE editor is initializing to ensure that we know which widget editor is active.

Here is what the default values for `before_widget` and `after_widget` are - https://codex.wordpress.org/Function_Reference/register_sidebar#Default_Usage.

Let us know if this helps.

Scott

**Comment by lmartins** [comment]
Hi @scottsousa,

Many thanks for your feedback here, and sorry for the late response.

I believe however I do have those elements present in source-code, please have a look into this screenshot taken from one of the affected sites:
https://infinit.io/_/H4UMBCz

Cheers

**Comment by lmartins** [comment]
I believe the JS error causing it the issue mentions the 73:

```
$widget_root = form_control.container.find( selectors.widget_root ),
```

And if so the `undefined` refers to `form_control` which is declared in the line immediately before:
```
var form_control = api.Widgets.getWidgetFormControlForWidget( data.widget.id )
```

**Comment by scottsousa** [comment]
Hi @lmartins,

Thank you for providing the screenshot. It looks like everything is in place.

You are correct about that line of JavaScript causing the error. That line of JS is looking for the widget ID value from the hidden input (seen in your screenshot) with a name attribute of `widget_id`. This control value *should* always be present in the Customizer JavaScript API controls collection.

Perhaps this a case where it's not present even though we're expecting it to be. We want to make sure that if this is a bug with Note, we fix it as soon as we can.

We just pushed [version 1.3.0](https://conductorplugin.com/conductor-and-note-version-1-3-0/) today. Would you be able to test with that version to see if the error still persists?

If it does, can you verify that the widget control exists within the Customizer sidebar section (Widgets > *Sidebar with Note Widget*)?

Thank You,
Scott

**Comment by lmartins** [comment]
Hi @scottsousa 
Congrats on the new release.

Im afraid the situation has gotten worse. I now can't event put my cursor in the widget to edit the content.

It seems it is still the same line affected:
https://www.dropbox.com/s/gx877zw25a7polp/Screenshot%202015-11-06%2019.47.17.png?dl=0

**Comment by sdsweb** [comment]
Hi @lmartins Any chance we can get a copy of your theme to test with?

**Comment by lmartins** [comment]
Hi @sdsweb, I have now reasons to believe this has something to do with our theme, at least it has interacts in some weird way with anything on our code. I'll try to pinpoint that. If I managed to achieve it, and if it is something worth mentioning to you, I'll reopen this ticket.

Until then, many thanks to you and @scottsousa for all the help provided.
